name: CI
on:
  pull_request:
    branches:
    - main
  push:
    branches:
      - main

jobs:
  first:
    runs-on: ubuntu-latest
    #continue-on-error: true
    steps:
      - name: print stuff and fail
        run: echo Hello Wordl! && false && exit -1

  second:
    runs-on: ubuntu-latest
    needs: [first]
    if: always()
    steps:
      - name: print stuff and pass
        run: echo Hello again!
    
