name: CI
on:
  pull_request:
    branches:
    - main
  push:
    branches:
      - main

jobs:
  first:
    runs-on: ubuntu-latest
    #continue-on-error: true
    steps:
      - name: print stuff and pass
        run: echo Hello Wordl!

  second:
    runs-on: ubuntu-latest
    needs: [first]
    if: always()
    steps:
      - name: print stuff and fail
        run: echo Hello again!  && false && exit -1
    
  third:
    runs-on: ubuntu-latest
    needs: [second]
    #if: ${{ contains(needs.*.result, 'success') }}
    if: always()
    steps:
      - name: print stuff and pass
        run: echo ${{ join(needs.*.result) }}
        
