name: Phony reusable workflow
on:
  workflow_call:
    inputs:
      runnersJson:
        description: 'set of tags for a runner'
        required: true
        type: string
jobs:
  runners_setup:
    runs-on: ubuntu-latest
    outputs:
      runners_tags: ${{ steps.setVariables.outputs.runners_tags }}
    steps:
      - name: debug
        uses: hmarr/debug-action@v2
      - name: Dump all the contextes
        run: |
            cat <<JSON
            ${{toJson(github)   }}
            JSON
            cat <<JSON
            ${{toJson(env)      }}
            JSON
            cat <<JSON
            ${{toJson(vars)     }}
            JSON
            cat <<JSON
            ${{toJson(job)      }}
            JSON
            cat <<JSON
            ${{toJson(steps)    }}
            JSON
            cat <<JSON
            ${{toJson(inputs)   }}
            JSON
            cat <<JSON
            ${{toJson(runner)   }}
            JSON
            cat <<JSON
            ${{toJson(needs)    }}
            JSON
            cat <<JSON
            ${{toJson(secrets)  }}
            JSON
      - id: setVariables
        run: |
          echo "runners_tags=$input" >> $GITHUB_OUTPUT
        #   echo "::set-output name=runners_tags::$input"
        env:
          input: ${{ inputs.runnersJson }}
  debug_contextes:
    runs-on: ${{fromJson(needs.runners_setup.outputs.runners_tags)}}
    needs: runners_setup
    steps:
      - uses: hmarr/debug-action@v2
      - name: Dump all the contextes
        run: |
            cat <<JSON
            ${{toJson(github)   }}
            JSON
            cat <<JSON
            ${{toJson(env)      }}
            JSON
            cat <<JSON
            ${{toJson(vars)     }}
            JSON
            cat <<JSON
            ${{toJson(job)      }}
            JSON
            cat <<JSON
            ${{toJson(steps)    }}
            JSON
            cat <<JSON
            ${{toJson(inputs)   }}
            JSON
            cat <<JSON
            ${{toJson(runner)   }}
            JSON
            cat <<JSON
            ${{toJson(needs)    }}
            JSON
            cat <<JSON
            ${{toJson(secrets)  }}
            JSON
