name: Phony reusable workflow
on:
  workflow_call:
    inputs:
      runners_tags:
        description: 'set of tags for a runner'
        required: true
        type: string
jobs:
  pre_debug_contextes:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: Dump all the contextes
        run: |
          cat <<JSON
          env: ${{toJson(env)      }}
          JSON
          cat <<JSON
          vars: ${{toJson(vars)     }}
          JSON
          cat <<JSON
          job: ${{toJson(job)      }}
          JSON
          cat <<JSON
          steps: ${{toJson(steps)    }}
          JSON
          cat <<JSON
          inputs: ${{toJson(inputs)   }}
          JSON
          cat <<JSON
          runner: ${{toJson(runner)   }}
          JSON
          cat <<JSON
          needs: ${{toJson(needs)    }}
          JSON
          cat <<JSON
          secrets: ${{toJson(secrets)  }}
          JSON

  runners_setup:
    needs: pre_debug_contextes
    runs-on: ubuntu-latest
    outputs:
      runners_tags: ${{ steps.setVariables.outputs.runners_tags }}
    steps:
      - id: setVariables
        name: Prepare variables for the later steps
        run: |
          # Prepend self-hosted to an JSON array
          input="self-hosted, ${input}"

          # Make something like a JSON array from comma-separated list
          input="['${input}']"
          input="${input//\,/\'\, \'}"

          echo "runners_tags=$input" >> ${GITHUB_OUTPUT}
        env:
          input: ${{ inputs.runners_tags }}

  post_debug_contextes:
    needs: runners_setup
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: Dump all the contextes
        run: |
            cat <<JSON
            env: ${{toJson(env)      }}
            JSON
            cat <<JSON
            vars: ${{toJson(vars)     }}
            JSON
            cat <<JSON
            job: ${{toJson(job)      }}
            JSON
            cat <<JSON
            steps: ${{toJson(steps)    }}
            JSON
            cat <<JSON
            inputs: ${{toJson(inputs)   }}
            JSON
            cat <<JSON
            runner: ${{toJson(runner)   }}
            JSON
            cat <<JSON
            needs: ${{toJson(needs)    }}
            JSON
            cat <<JSON
            secrets: ${{toJson(secrets)  }}
            JSON

  bogus_run:
    needs: runners_setup
    runs-on: ${{ fromJson(needs.runners_setup.outputs.runners_tags) }}
    timeout-minutes: 1
    steps:
        - name: bogus step
          run: true
