name: Phony reusable workflow
on:
  workflow_call:
    inputs:
      runnersJson:
        description: 'set of tags for a runner'
        required: true
        type: string
jobs:
  pre_debug_contextes:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: Dump all the contextes
        run: |
          cat <<JSON
          env: ${{toJson(env)      }}
          JSON
          cat <<JSON
          vars: ${{toJson(vars)     }}
          JSON
          cat <<JSON
          job: ${{toJson(job)      }}
          JSON
          cat <<JSON
          steps: ${{toJson(steps)    }}
          JSON
          cat <<JSON
          inputs: ${{toJson(inputs)   }}
          JSON
          cat <<JSON
          runner: ${{toJson(runner)   }}
          JSON
          cat <<JSON
          needs: ${{toJson(needs)    }}
          JSON
          cat <<JSON
          secrets: ${{toJson(secrets)  }}
          JSON

  runners_setup:
    needs: pre_debug_contextes
    runs-on: ubuntu-latest
    outputs:
      runners_tags: ${{ steps.setVariables.outputs.runners_tags }}
    steps:
      - id: setVariables
        name: Prepare variables for the later steps
        run: |
          echo $input
          echo ${input/\[/\[\'self-hosted\',} # prepend self-hosted to the runner tags
          set -x
          echo "${{ fromJson(env.input) || fromJson(format('[{0}]', env.input)) }}"
          echo ${{ toJson('foobar') }}
          echo ${{ startsWith('[', env.input)}}
          echo "runners_tags=$input" >> ${GITHUB_OUTPUT}
        env:
          input: ${{ inputs.runnersJson }}

  post_debug_contextes:
    needs: runners_setup
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: Dump all the contextes
        run: |
            cat <<JSON
            env: ${{toJson(env)      }}
            JSON
            cat <<JSON
            vars: ${{toJson(vars)     }}
            JSON
            cat <<JSON
            job: ${{toJson(job)      }}
            JSON
            cat <<JSON
            steps: ${{toJson(steps)    }}
            JSON
            cat <<JSON
            inputs: ${{toJson(inputs)   }}
            JSON
            cat <<JSON
            runner: ${{toJson(runner)   }}
            JSON
            cat <<JSON
            needs: ${{toJson(needs)    }}
            JSON
            cat <<JSON
            secrets: ${{toJson(secrets)  }}
            JSON

  bogus_run:
    needs: runners_setup
    runs-on: ${{ fromJson(needs.runners_setup.outputs.runners_tags) }}
    timeout-minutes: 1
    steps:
        - name: bogus step
          run: true
