name: Phony reusable workflow
on:
  workflow_call:
    inputs:
      runnersJson:
        description: 'set of tags for a runner'
        required: true
        type: string
jobs:
  runners_setup:
    runs-on: ubuntu-latest
    outputs:
      runners_tags: ${{ steps.setVariables.outputs.runners_tags }}
    steps:
      - id: setVariables
        run: |
          echo we need to format RUNNERS_ARRAY as JSON array even when we have a single value there: $input
          RUNNERS_ARRAY=${{ fromJson(inputs.runnersJson) || format('[{0}]', inputs.runnersJson) }}
          echo $RUNNERS_ARRAY
          echo "runners_tags=$RUNNERS_ARRAY" >> $GITHUB_OUTPUT
        env:
          input: ${{ inputs.runnersJson }}

  debug_contextes:
    needs: runners_setup
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: Dump all the contextes
        run: |
            cat <<JSON
            github: ${{toJson(github)   }}
            JSON
            cat <<JSON
            env: ${{toJson(env)      }}
            JSON
            cat <<JSON
            vars: ${{toJson(vars)     }}
            JSON
            cat <<JSON
            job: ${{toJson(job)      }}
            JSON
            cat <<JSON
            steps: ${{toJson(steps)    }}
            JSON
            cat <<JSON
            inputs: ${{toJson(inputs)   }}
            JSON
            cat <<JSON
            runner: ${{toJson(runner)   }}
            JSON
            cat <<JSON
            needs: ${{toJson(needs)    }}
            JSON
            cat <<JSON
            secrets: ${{toJson(secrets)  }}
            JSON

  bogus_run:
    needs: runners_setup
    runs-on: ${{ fromJson(needs.runners_setup.outputs.runners_tags) }}
    timeout-minutes: 1
    steps:
        - name: bogus step
          run: true
