name: Phony reusable workflow
on:
  workflow_call:
    inputs:
      runnersJson:
        description: 'set of tags for a runner'
        required: true
        type: string
jobs:
  runners_setup:
    runs-on: ubuntu-latest
    outputs:
      runners_tags: ${{ steps.setVariables.outputs.runners_tags }}
    steps:
      - name: debug
        uses: hmarr/debug-action@v2
      - name: Dump all the contextes
        run: |
            cat github:   ${{toJson(github)   }}
            cat env:      ${{toJson(env)      }}
            cat vars:     ${{toJson(vars)     }}
            cat job:      ${{toJson(job)      }}
            cat steps:    ${{toJson(steps)    }}
            cat runner:   ${{toJson(runner)   }}
            cat secrets:  ${{toJson(secrets)  }}
            cat needs:    ${{toJson(needs)    }}
            cat inputs:   ${{toJson(inputs)   }}
      - id: setVariables
        run: |
          echo "::set-output name=runners_tags::$input"
        env:
          input: ${{ inputs.runnersJson }}
  debug_contextes:
    runs-on: ${{fromJson(needs.runners_setup.outputs.runners_tags)}}
    needs: runners_setup
    steps:
      - uses: hmarr/debug-action@v2
      - name: Dump all the contextes
        run: |
            cat github:   ${{toJson(github)   }}
            cat env:      ${{toJson(env)      }}
            cat vars:     ${{toJson(vars)     }}
            cat job:      ${{toJson(job)      }}
            cat steps:    ${{toJson(steps)    }}
            cat runner:   ${{toJson(runner)   }}
            cat secrets:  ${{toJson(secrets)  }}
            cat needs:    ${{toJson(needs)    }}
            cat inputs:   ${{toJson(inputs)   }}
